import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { Project, Asset, ImageBlock } from '../types';

// A4サイズ (mm)
const A4_WIDTH = 210;
const A4_HEIGHT = 297;

export interface PDFExportOptions {
  scale: number;   // 解像度倍率 (1=普通, 2=高画質)
  quality: number; // JPEG圧縮率 (0.1 ~ 1.0)
  filenameSuffix?: string; // ファイル名の接尾辞 (_compressed 等)
}

export const generatePDF = async (
  project: Project, 
  assets: Asset[],
  onProgress: (msg: string) => void,
  options: PDFExportOptions = { scale: 2, quality: 0.9 } // デフォルトは高画質
) => {
  // 1. PDF初期化
  const pdf = new jsPDF('p', 'mm', 'a4');
  const getAssetUrl = (id: string | null) => assets.find(a => a.id === id)?.url || '';

  // 2. 一時的なレンダリング用コンテナを作成（画面外）
  const container = document.createElement('div');
  container.style.position = 'fixed';
  container.style.top = '-10000px';
  container.style.left = '-10000px';
  container.style.width = '210mm'; // A4幅
  container.style.minHeight = '297mm'; // A4高さ
  container.style.backgroundColor = '#ffffff';
  container.style.color = '#000000';
  container.style.fontFamily = '"Helvetica Neue", Arial, sans-serif';
  document.body.appendChild(container);

  // --- Helper: HTMLからCanvas化してPDFに追加 ---
  const captureAndAddPage = async (isFirstPage: boolean) => {
    // 画像の読み込み待ち
    const images = container.querySelectorAll('img');
    await Promise.all(Array.from(images).map(img => {
      if (img.complete) return Promise.resolve();
      return new Promise(resolve => { img.onload = resolve; img.onerror = resolve; });
    }));

    // html2canvasで撮影 (★options.scale を適用)
    const canvas = await html2canvas(container, {
      scale: options.scale, 
      useCORS: true,
      logging: false,
    });

    // JPEG圧縮 (★options.quality を適用)
    const imgData = canvas.toDataURL('image/jpeg', options.quality);
    
    if (!isFirstPage) pdf.addPage();
    pdf.addImage(imgData, 'JPEG', 0, 0, A4_WIDTH, A4_HEIGHT);
  };

  try {
    // ==========================================
    // 1. 表紙 (Cover Page)
    // ==========================================
    onProgress("表紙を生成中...");
    const coverUrl = getAssetUrl(project.coverAssetId);
    
    container.innerHTML = `
      <div style="padding: 40px; height: 297mm; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center;">
        <h1 style="font-size: 42px; margin-bottom: 20px; font-weight: bold; color: #333;">${project.title}</h1>
        <div style="margin-bottom: 30px; display: flex; gap: 10px; justify-content: center;">
          <span style="border: 1px solid #666; padding: 5px 15px; border-radius: 20px; font-size: 14px;">${project.gachaResult.themeA}</span>
          <span style="border: 1px solid #666; padding: 5px 15px; border-radius: 20px; font-size: 14px;">${project.gachaResult.themeB}</span>
          <span style="background: #eee; padding: 5px 15px; border-radius: 20px; font-size: 14px;">★ ${project.gachaResult.secretIngredient}</span>
        </div>
        
        <div style="width: 80%; aspect-ratio: 2/3; background: #eee; margin-bottom: 30px; overflow: hidden; border: 4px solid #333;">
          ${coverUrl ? `<img src="${coverUrl}" style="width: 100%; height: 100%; object-fit: cover;" />` : '<div style="padding-top: 50%;">NO IMAGE</div>'}
        </div>

        <p style="font-size: 18px; line-height: 1.8; color: #555; max-width: 80%; margin-bottom: 40px; font-style: italic;">
          ${project.synopsis}
        </p>

        <div style="border-top: 1px solid #ccc; padding-top: 20px; width: 100%;">
          <p style="font-size: 12px; color: #999;">Generated by AI Manga Studio</p>
        </div>
      </div>
    `;
    await captureAndAddPage(true);

    // ==========================================
    // 2. 本編ページ (Story Pages)
    // ==========================================
    
    // 画像ブロックのみ抽出
    const imageBlocks = project.storyboard.filter(b => b.type === 'image') as ImageBlock[];

    for (let i = 0; i < imageBlocks.length; i++) {
      onProgress(`ページ生成中 (${i + 1}/${imageBlocks.length})...`);
      const page = imageBlocks[i];
      const pageUrl = getAssetUrl(page.assignedAssetId);

      container.innerHTML = `
        <div style="height: 297mm; position: relative; background: #000;">
          <div style="width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;">
            ${pageUrl 
              ? `<img src="${pageUrl}" style="max-width: 100%; max-height: 100%; object-fit: contain;" />` 
              : '<div style="color: white;">NO IMAGE</div>'
            }
          </div>

          <div style="position: absolute; bottom: 50px; left: 50%; transform: translateX(-50%); width: 90%; background: rgba(0,0,0,0.8); color: white; padding: 20px; border-radius: 10px; border: 2px solid #555; text-align: center;">
            <p style="font-size: 24px; font-weight: bold; line-height: 1.5; margin: 0;">
              ${page.dialogue}
            </p>
          </div>

          <div style="position: absolute; bottom: 15px; right: 20px; color: #999; font-size: 14px;">
            - ${page.pageNumber} -
          </div>
        </div>
      `;
      await captureAndAddPage(false);
    }

    // 保存
    onProgress("保存中...");
    const suffix = options.filenameSuffix || '';
    pdf.save(`${project.title}${suffix}.pdf`);

  } catch (e) {
    console.error(e);
    alert("PDF生成に失敗しました");
  } finally {
    document.body.removeChild(container);
  }
};
