runtime: nodejs20
automatic_scaling:
  min_instances: 1

inbound_services:
  - warmup

handlers:
  # 修正点：APIへのリクエストは、すべてアプリケーションで処理するように明示します。
  - url: /api/.*
    script: auto
    secure: always

  # API以外の.pngなどの静的ファイルリクエストを処理します。
  - url: /(.*\.(css|js|png|gif|svg))$
    static_files: public/\1
    upload: public/.*\.(css|js|png|gif|svg)$

  - url: /_ah/warmup
    script: auto
    secure: always

  # その他のすべてのリクエストをアプリケーションで処理します。
  - url: /.*
    script: auto
    secure: always
