runtime: nodejs20
automatic_scaling:
  min_instances: 1

inbound_services:
  - warmup

handlers:
  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico

  # /js/ 以下のすべてのリクエストを静的ファイルとして扱う
  - url: /js/(.*)
    static_files: public/js/\1
    upload: public/js/(.*)

  # CSSや他の静的ファイルも同様の記述が確実です
  - url: /(.*\.(css|png|gif|svg))$
    static_files: public/\1
    upload: public/.*\.(css|png|gif|svg)$

  # APIへのリクエストは、すべてアプリケーションで処理するように明示します。
  - url: /api/.*
    script: auto
    secure: always

  - url: /_ah/warmup
    script: auto
    secure: always

  # その他のすべてのリクエストをアプリケーションで処理します。
  - url: /.*
    script: auto
    secure: always