runtime: nodejs20
automatic_scaling:
  min_instances: 1

inbound_services:
  - warmup

handlers:
  - url: /(.*\.(css|js|png|gif|svg))$
    static_files: public/\1
    upload: public/.*\.(css|js|png|gif|svg)$

  - url: /_ah/warmup
    script: auto
    secure: always

  - url: /.*
    script: auto
    secure: always